### ISSUE TITLE
Add hard and easy mode 

### ISSUE THREAD

**Issue by octokatherine** [octokatherine/word-master#6]
I'd like to have a setting where the user can put the game in hard or easy mode.

Easy mode: guesses don't have to be valid words
Normal mode: how it currently works
Hard mode: any revealed hints must be used in subsequent guesses (can look at Wordle's implementation of this)

There should be a settings icon + modal added where a user can change this setting. Default should be normal mode. Could save the user's settings in local storage

**Comment by Sam0ht** [comment]
Do you think the user should be able to change the difficulty level mid-game, or should changing the mode also start a new game?

I intend to have a go at this; I'm moderately confident about implementing the game logic, less so about the UI to control it.

**Comment by octokatherine** [comment]
I believe wordle allows changing the difficulty level mid-game. Let's go with that to start

**Comment by ckjpn** [comment]
### Instead of....
_Easy mode: guesses don't have to be valid words
Normal mode: how it currently works
Hard mode: any revealed hints must be used in subsequent guesses (can look at Wordle's implementation of this)_

### I'd suggest working on offering different sets of words.

1. **Easy:** Limited to very high-frequency words that even elementary school children would know.
2. **Normal:** Limited to high-frequency words -- everyday words that adults use.
3. **Difficult:** Less frequently-word words, but words most native speakers have in their passive memory, even though they don't usually use them.
4. **Very Difficult"** Maybe even have a level like this with words that most people don't know, but Scrabble player learn.

**Comment by ckjpn** [comment]
I tried creating an easy mode, but ended up getting real words not on the easy mode list marked as "not words" with red circles.

This means that I did it wrong, or that there will need to be 2 lists: one with the easy words and one with all words.

Here's a screenshot.

<img width="741" alt="Screen Shot 2022-01-19 at 12 25 57" src="https://user-images.githubusercontent.com/7934273/150058773-eb3319d3-0c31-4a48-a0e2-ffac97fd6cae.png">

**Comment by rcatwood** [comment]
'Hard mode' as in Wordle changes the strategy (and is 'a better game' according to some) Using a bigger word list does not really change the game much. 
If my vote is worth anything :) , I vote for the "Hard mode: any revealed hints must be used in subsequent guesses" , becuase I'd like to play that version ! (though I  suppose i can  try to follow those rules anyways) 
 while a separate option for extended word list could be (a different feature request?)  

I have it on good authority that the Wordle code uses one list for the target word of the day , and a different , bigger, list for the validation of guessed words. For example, (very minor spoiler) I understand that 'zymic' is in the validation list but will never appear as a target word.

**Comment by Sam0ht** [comment]
Ok, issue #85 connects to the provided settings widget in the dialog and implements Easy and Hard modes.

**Comment by octokatherine** [comment]
> It does not (as of today), it would not let me change the mode after making a guess.

@rcatwood you're right, he must have changed that! I used to be able to switch it mid-game

**Comment by octokatherine** [comment]
It's more important on Wordle to prevent changing mid-game since it's part of the stats tracked. In this game there is nothing tracked that says what mode you were in, its more of just a personal challenge so I feel okay about leaving it up to the user.
