### ISSUE TITLE
Hardware 'Enter' key repeats most recent mouse input

### ISSUE THREAD

**Issue by doopl** [octokatherine/word-master#8]
This issue occurs on Windows with Firefox and Edge browsers.

After the software keyboard has been clicked with a mouse, pressing Enter on a hardware keyboard inputs the last letter clicked.

If the info button was clicked last, pressing Enter opens the how to play modal.

Both of these actions are disruptive to play. I believe the only function of Enter during a game should be to check the currently input word.

**Comment by octokatherine** [comment]
Thanks for the report! This could definitely be smoother.

In the meantime, would using the hardware keyboard to input letters instead of the software keyboard improve your experience? My expectation was that users would usually use only a hardware keyboard or only the software keyboard (on mobile probably)

**Comment by doopl** [comment]
Thanks. Yeah I was mostly typing. I think sometimes when I would carefully look at which letters I hadn't used I'd mouse around the software keyboard and that would lead to me clicking.

**Comment by Sam0ht** [comment]
I have a fix for this I think, calling event.preventDefault(), just trying to sort my repo out to raise the PR.

**Comment by doopl** [comment]
Thanks for the fix!
