### ISSUE TITLE
Remove Plural / derived word from the answers.js?

### ISSUE THREAD

**Issue by arzenvald** [octokatherine/word-master#87]
Too many plural and derived words that doesn't meant to be 5 letters word (such as sixes, avows, maker, etc.)

I think plurals are one that I find odd to answer

**Comment by octokatherine** [comment]
I get a lot of requests to remove words from the answers list for various reasons, and I don't want to keep doing that because I don't want the word list to get too small. I already get complaints about people getting repeat words because of the size of the list. 

Sorry, I can't make everyone happy 😬
